//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Theater
{
    using System;
    using System.Collections.Generic;
    
    public partial class Performances
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Performances()
        {
            this.Roles = new HashSet<Roles>();
        }
    
        public int PerformanceId { get; set; }
        public int PlayId { get; set; }
        public System.DateTime PerformanceDate { get; set; }
        public System.DateTime PerformanceTime { get; set; }
        public string PerformanceLocation { get; set; }
        public string PerformancePrice { get; set; }
        public string PerformanceDresser { get; set; }
        public string PerformanceDirector { get; set; }
        public string PerformanceArtDirector { get; set; }
    
        public virtual Plays Plays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Roles> Roles { get; set; }
    }
}
