//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Theater
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plays
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Plays()
        {
            this.Performances = new HashSet<Performances>();
        }
    
        public int PlayId { get; set; }
        public int GenreId { get; set; }
        public int ParentalGuidanceId { get; set; }
        public string PlayName { get; set; }
        public string PlayAuthor { get; set; }
        public string PlayPremiere { get; set; }
    
        public virtual Genres Genres { get; set; }
        public virtual ParentalGuidances ParentalGuidances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Performances> Performances { get; set; }
    }
}
