//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Theater
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TheaterDBContext : DbContext
    {
        public TheaterDBContext()
            : base("name=TheaterDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Genres> Genres { get; set; }
        public virtual DbSet<ParentalGuidances> ParentalGuidances { get; set; }
        public virtual DbSet<Performances> Performances { get; set; }
        public virtual DbSet<Plays> Plays { get; set; }
        public virtual DbSet<Professions> Professions { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
